## ===========================================
## application-prod.yml - Configuration production
## ===========================================
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 10
#
#  jpa:
#    show-sql: false
#
#logging:
#  level:
#    com.projectsaas.auth: INFO
#    org.springframework.security: WARN
#    org.hibernate: WARN
#
## JWT production
#jwt:
#  secret: ${JWT_SECRET}
#  expiration: ${JWT_EXPIRATION:86400000}
#  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}