spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.projectsaas.file: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.multipart: DEBUG

# Services externes en local
auth-service:
  base-url: http://localhost:8081

project-service:
  base-url: http://localhost:8082

# Stockage local pour dev
storage:
  provider: local
  local:
    base-path: ./temp-storage  # ← Changé de dev-files à temp-storage

# Antivirus désactivé en dev
antivirus:
  enabled: false