# Configuration développement - même pattern que notification-service
spring:
  config:
    activate:
      on-profile: dev

  # Même base de données que notification mais avec schema analytics_db
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_project_db_dev?currentSchema=analytics_db

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false

  kafka:
    consumer:
      group-id: analytics-service-dev

# Configuration analytics pour dev
analytics:
  calculation:
    interval: 60000 # 1 minute for dev
  reports:
    auto-generation: true

logging:
  level:
    com.projectsaas.analytics: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: DEBUG


#
## Configuration développement - même pattern que notification-service
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  # Même base de données que notification mais avec schema analytics_db
#  datasource:
#    url: jdbc:postgresql://localhost:5432/saas_project_db_dev?currentSchema=analytics_db
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  flyway:
#    clean-disabled: false
#
#  # ❌ Configuration Kafka (DÉSACTIVÉE pour dev)
#  kafka:
#    enabled: false
#    # consumer:
#    #   group-id: analytics-service-dev
#
## ❌ Configuration Eureka (DÉSACTIVÉE pour dev)
#eureka:
#  client:
#    enabled: false
#
## Configuration analytics pour dev
#analytics:
#  calculation:
#    interval: 60000 # 1 minute for dev
#  reports:
#    auto-generation: true
#
#logging:
#  level:
#    com.projectsaas.analytics: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    # org.springframework.kafka: DEBUG  # Commenté car Kafka désactivé