# Configuration développement - même pattern que tes autres services
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false

logging:
  level:
    com.projectsaas.notification: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.mail: DEBUG

# Configuration mail pour dev (plus permissive)

  mail:
    properties:
      mail:
        smtp:
          trust: "*"
        debug: true

# Configuration notification pour dev
notification:
  websocket:
    allowed-origins: "*"