# ==========================================
# application-docker.yml - File Service Docker
# ==========================================
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/saas_project_db_dev?currentSchema=file_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: file_db

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:-50MB}
      max-request-size: ${MAX_FILE_SIZE:-50MB}

# Services externes
auth-service:
  base-url: ${AUTH_SERVICE_URL}

project-service:
  base-url: http://project-service:8082

# Configuration de stockage
storage:
  provider: local
  local:
    base-path: ${UPLOAD_PATH:-/app/temp-storage}

# Antivirus desactive
antivirus:
  enabled: false

logging:
  level:
    com.projectsaas.file: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"