spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:50MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

server:
  port: ${SERVER_PORT:8083}

auth-service:
  base-url: ${AUTH_SERVICE_URL}

project-service:
  base-url: ${PROJECT_SERVICE_URL}

storage:
  local:
    upload-dir: ${UPLOAD_DIR:/tmp/uploads}

logging:
  level:
    com.projectsaas.file: INFO
    root: WARN




#server:
#  port: ${SERVER_PORT:8083}
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: ${DB_POOL_SIZE:50}
#      minimum-idle: ${DB_POOL_MIN:10}
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: false
#    properties:
#      hibernate:
#        default_schema: ${DATABASE_SCHEMA:file_db}
#
#  servlet:
#    multipart:
#      max-file-size: ${MAX_FILE_SIZE:500MB}
#      max-request-size: ${MAX_REQUEST_SIZE:500MB}
#
## Services externes en production
#auth-service:
#  base-url: ${AUTH_SERVICE_URL}
#
#project-service:
#  base-url: ${PROJECT_SERVICE_URL}
#
## Stockage cloud en production
#storage:
#  provider: ${STORAGE_PROVIDER:s3}
#  s3:
#    bucket: ${S3_BUCKET}
#    access-key: ${S3_ACCESS_KEY}
#    secret-key: ${S3_SECRET_KEY}
#    region: ${S3_REGION}
#
## Antivirus active en production
#antivirus:
#  enabled: ${ANTIVIRUS_ENABLED:true}
#  engine: ${ANTIVIRUS_ENGINE:clamav}
#
## Logging minimal en production
#logging:
#  level:
#    com.projectsaas.file: INFO
#    org.springframework.security: WARN
#    org.hibernate: WARN
#    root: WARN
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"