# ===========================================
# application-dev.yml - Configuration développement
# ===========================================
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.projectsaas.project: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Services externes en local
auth-service:
  base-url: http://localhost:8081

websocket:
  allowed-origins: "*"
